[package]
name = "iexcloud"
version = "0.1.0"
authors = ["rHermes <teodor@spaeren.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
